// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoWP8IqW39JCwjiv_t12aP9ZyM1GO_9uw',
    appId: '1:871283740153:web:8b5d9e2232c0aac00c8128',
    messagingSenderId: '871283740153',
    projectId: 'freshcart-471b6',
    authDomain: 'freshcart-471b6.firebaseapp.com',
    storageBucket: 'freshcart-471b6.firebasestorage.app',
    measurementId: 'G-14GFVGP2H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMC8QHxpCxb9iHkBLypjmgvLQ5kLyA_4',
    appId: '1:871283740153:android:4684c02ed922806a0c8128',
    messagingSenderId: '871283740153',
    projectId: 'freshcart-471b6',
    storageBucket: 'freshcart-471b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiOmEkC-UID-bUuzA3NY_MJgOAZoVi0Ks',
    appId: '1:871283740153:ios:e2cdbc352678ab010c8128',
    messagingSenderId: '871283740153',
    projectId: 'freshcart-471b6',
    storageBucket: 'freshcart-471b6.firebasestorage.app',
    androidClientId: '871283740153-33n0uej5k0p5g3hj09dsb6iejdp6j8bv.apps.googleusercontent.com',
    iosClientId: '871283740153-2i06qsqjffhrp7stoopadvi5mnr4171c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiOmEkC-UID-bUuzA3NY_MJgOAZoVi0Ks',
    appId: '1:871283740153:ios:e2cdbc352678ab010c8128',
    messagingSenderId: '871283740153',
    projectId: 'freshcart-471b6',
    storageBucket: 'freshcart-471b6.firebasestorage.app',
    androidClientId: '871283740153-33n0uej5k0p5g3hj09dsb6iejdp6j8bv.apps.googleusercontent.com',
    iosClientId: '871283740153-2i06qsqjffhrp7stoopadvi5mnr4171c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoWP8IqW39JCwjiv_t12aP9ZyM1GO_9uw',
    appId: '1:871283740153:web:37a78ec34b06ad190c8128',
    messagingSenderId: '871283740153',
    projectId: 'freshcart-471b6',
    authDomain: 'freshcart-471b6.firebaseapp.com',
    storageBucket: 'freshcart-471b6.firebasestorage.app',
    measurementId: 'G-WJPEHK6C3M',
  );
}
